# Generated by Django 6.0.6 on 2026-06-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view_book', 'Can view book'), ('can_add_book', 'Can add book'), ('can_edit_book', 'Can edit book'), ('can_delete_book', 'Can delete book')]},
        ),
    ]
